server:
  port: 8081
  servlet:
    context-path: /jwt
  
spring:
  security:
    user:
      name: rahul
      password: rahul

  datasource:
    driver-class-name: jdbc:mysql://localhost:3306/rahuldb?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 
    