server:
  port: 8081
  servlet:
    context-path: /studentApp
    
#Database and Hibernate Properties    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rahuldb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
